version: "3.0"

services:
  webapp:
    container_name: "noop_server"
    restart: "always"
    build: "./"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://database:3306/noop"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    networks:
      - "noop_net"

networks:
  noop_net:
