version: "3.0"

services:
  database:
    container_name: "noop_db"
    image: "mariadb"
    environment:
      MARIADB_DATABASE: "noop"
      MARIADB_ROOT_PASSWORD: "1234"
    volumes:
      - "noop_db"
    ports:
      - "3306:3306"
    networks:
      - "noop_net"

  webapp:
    container_name: "noop_server"
    restart: "always"
    build: "./"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://database:3306/noop"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - "database"
    networks:
      - "noop_net"

networks:
  noop_net:
